### ISSUE TITLE
3.0.1 Runtime errors when using `cast`

### ISSUE THREAD

**Issue by alechenninger** [tonio-ramirez/optional.dart#9]
When I have time I can give a code example, but the basic setup was an Optional of type  T (absent), casted to R (`.cast<R>()`) and then `orElse(instanceOfR)` was throwing a runtime error which described the problem as expected T but got R.

On 3.0.0, I do not get this error.

**Comment by tonio-ramirez** [comment]
I was unable to reproduce.  Which version of Dart are you using?  I added a test for this, and ran all tests with versions 2.0.0, 2.1.1, and 2.2.0, and had no problem.  On the other hand, I did find and fix a problem with `cast()` when applied to present (rather than absent) instances of `Optional`.

**Comment by alechenninger** [comment]
I'm using dev channel of dart. I will try to create a test case this weekend and try stable as well. Thank you.

**Comment by tonio-ramirez** [comment]
I was unable to reproduce using dev version 2.3.0-dev.0.5 (the current dev channel version).  In any case, I have pushed and published version 3.0.2, which fixes a present `cast()` issue.  Maybe try that, and see if the issue is gone?

**Comment by alechenninger** [comment]
Working now with 3.0.2. I must've had the setup wrong in my head. Thanks so much!
